### PR TITLE
image reduce 40%, of tsc file

### PR DESCRIPTION
**Pull request by Arnab7456**
1. Refactored Dockerfile to implement a multi-stage build, separating the build environment from the runtime environment.
2. Ensured TypeScript compilation occurs in the build stage, reducing the final image size by excluding unnecessary development dependencies.
3. Updated the Dockerfile to install only production dependencies in the final image.

### CODE REVIEW

**Comment by frankhart2018** [comment]
Was the container tested?

**Comment by Arnab7456** [comment]
Yes, the container was tested in the runtime environment. It runs as expected with only the necessary production dependencies included, resulting in a significantly reduced image size

**Comment by frankhart2018** [comment]
Can you please post screenshots of the running app, after running the container.

**Comment by Arnab7456** [comment]
ok, you can check docker ps command that shows container run on port 8000
Screenshot from 2024-08-19 00-41-26
Screenshot from 2024-08-19 00-41-35

**Comment by frankhart2018** [comment]
Awesome, merging.

**Review by frankhart2018 — APPROVED** [review]

**Pull request merged**
