### PR TITLE
chore: Refactor routing in App component and introduce RouterProvider

### PR DESCRIPTION
**Pull request by MinavKaria**
## Description (Issue #127  )

Updated the react router dom to version 6 with createBrowserRouter 

## Motivation and Context

It is important to stay updated and version 6 makes the route creation **very easy** by just adding

Too add a page in route you have to just add a object with path and element , we can also make a layout, which can be added in further improvements, the basic simple structure to add a new page is given below which makes it easier to developer to add page, and have a dedicated file for showing and editing all the pages having it and making `App.tsx` clean

```
 {
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```
Thus making it easier for the beginners to add a page route and made the routes proper for better SEO

## How Has This Been Tested?

Checked every route before committing , Fortunately all the routes work properly as previous.

## Screenshots (if appropriate):

No visual feature as such so will be need to run on local environment to check the changes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by frankhart2018** [comment]
I will take a look at that today.

**Comment by MinavKaria** [comment]
@frankhart2018 
Ok, I am a contributor from GSSOC, so pls tag it accordingly.

**Comment by MinavKaria** [comment]
@frankhart2018 Did you check ?

**Review by frankhart2018 — APPROVED** [review]

**Comment by MinavKaria** [comment]
@frankhart2018 Please mark it GSSOC and the level

**Pull request merged**
