### PR TITLE
bug: Changed font family to monospace

### LINKED ISSUE #48: Change font family
The current font family makes it very hard to distinguish between lowercase L (l) and uppercase I (I). Which leads to confusion while using the passwords.

### PR DESCRIPTION
**Pull request by devmusiczz**
@frankhart2018 fix #48

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
There should be a way to do this globally, mixing fonts doesn't sound like a good idea. And it's not added to DecryptPassword, where it's required the most.

**Comment by frankhart2018** [comment]
You may find this useful: https://stackoverflow.com/questions/63526780/how-to-set-a-global-font-family-in-react-js

**Comment by devmusiczz** [comment]
@frankhart2018 added the font globally.

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
This somehow changes, the SquareTable component, and that component is compiled to an image which breaks now. Feel free to ping me in Discord  - `Siddhartha|PA|PrimiStore` if you want to discuss this there.

**Comment by devmusiczz** [comment]
@frankhart2018 resolved the issue.

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
It's still messing up the overall generated image. I think the SquareTable needs to be overriden to have the previous font.

**Comment by frankhart2018** [comment]
Closing this. Please re-open if you want to wrap this up.

**Pull request closed without merging**
