### PR TITLE
wiki-page

### PR DESCRIPTION
**Pull request by anglerfishlyy**
**fixes#87**

- This PR tries to create a Wiki page on Image‐Decryption Microservice Design.

- This includes your required specifications.

1.Brief description of the microservice.
2.State diagram for all the endpoints and one liner explanation of the microservice.
3.Link to the image decryption algorithm (already existing wiki) to explain that.

- Do check in wiki tab of [anglerfishlyy/primistore](https://github.com/anglerfishlyy/primistore).

### CODE REVIEW

**Comment by frankhart2018** [comment]
Looks good, please add this link to README.

**Review by frankhart2018 — APPROVED** [review]

**Comment by frankhart2018** [comment]
Why is there a submodule here?

**Comment by anglerfishlyy** [comment]
I 

> Why is there a submodule here?


I tried to delete it . I am new to all of this (open source ). I don't know how to do it. What should i do now?

**Comment by frankhart2018** [comment]
Create a new CR, do not commit to the wiki repository. Maybe just mail me the contents at sdharchou@gmail.com. And make a commit to add the link to the wiki page.

**Pull request merged**
