### PR TITLE
making list password as the default route  and removing the Home page

### LINKED ISSUE #73: Home page is not really required
The home page (MainMenu component) with all the links is not really required, the default home can be ListPasswords component. And all the links are already in navbar, there's no need for duplicating all the links in home page.

### PR DESCRIPTION
**Pull request by SumitKumar-17**
removing the Home Page and changing the routes, making List password as the default route,removing the MainMenu.js page Issue-73
I have removed the mainMenu Component and made the ListPasswords as the default "/" route as the issue requirements"

Closes #73

### CODE REVIEW

**Review by frankhart2018 — APPROVED** [review]
Awesome! Looks good. Thanks for your contribution :)

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
I take the approval back, there's one last change required in ListPasswords to load the password (i.e. call the API) on page load. Hint: It's related to updating the target of useEffect.

**Comment by SumitKumar-17** [comment]
I feel that you are referring to the useEffect on the Listpassword.js to which should call the APi on page load . 
I updated it as 
 useEffect(() => {
    dispatch(fetchPasswordsThunk());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

**Review by frankhart2018 — APPROVED** [review]
Yup that was what I was looking for. Looks good now. Merging.

**Pull request merged**
